# 不要在配置文件中使用制表符

# Site Settings
title: "niuyongjie.tk"
url: "https://niuyongjie.tk"
google_email: "yongjoeniu92@gmail.com"
description: "一名老是折腾其他其技术的Java软件工程师"

# Author Settings
author_name: "牛勇杰"
author_url: "https://niuyongjie.tk"
author_bio: "一名老是折腾其他其技术的Java软件工程师"

# Social Settings
github_url: "https://github.com/niuyongjie"

# Global Settings
Encoding: utf-8
defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
  -
    scope:
      path: "_posts"
    values:
      author: "Niu Yongjie"

# Build Settings
markdown: kramdown
#permalink: /blog/:year/:month/:day/:title
future: ture # 允许发布未来日期
show_drafts: true # 渲染草稿posts
unpublished: true # 渲染包含unpublished的posts
#lsi: true # 生成相关帖子的索引
incremental: false # 只构建需要重新构建的posts和pages页面
profile: true # 在build的时候打印列表,显示耗费资源信息,来帮助提升性能

# Serve Command Options 

port: 8080 # 监听8080端口
detach: true # 分离服务启动线程
#show_dir_listing: true
baseurl: "" # 不包含hostname


# theme style
style: styles-2

# Profile Information
name: 牛勇杰
tagline: Java 软件工程师
pic: profile.png

# Sidebar links
email: "1054602234@qq.com"
phone: 170 0010 4677
website: niuyongjie.tk
github: "niuyongjie"

